version: '2'
services:
  mariadb_service:
    image: mariadb_service
    container_name: mariadb_service
    build : 
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      args:
        - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
        - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
        - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
    restart: always
    networks:
      - inception
    volumes:
      - dataBase:/var/lib/mysql
    env_file:
      - .env
  wordpress_service:
    image: wordpress_service
    depends_on:
      - mariadb_service
    container_name: wordpress_service
    build :
       context:  ./requirements/wordpress
       dockerfile: Dockerfile
       args:
        - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
        - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
        - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
        - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
    restart: always
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
  nginx_service:
    image: nginx_service
    depends_on:
      - wordpress_service
    build :
      context: ./requirements/nginx 
      dockerfile: Dockerfile
    restart: always
    ports: 
      - "443:443" 
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
networks:
  inception:
    name: inception
    driver: bridge
volumes:
  dataBase:
    driver: local
    driver_opts:
      type: none
      device: /home/kel-baam/data/mariadb
      o: bind
  wordpress:
    driver: local
    driver_opts:
        type: none
        device: /home/kel-baam/data/wordpress
        o: bind


